apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environment }}-{{ .Values.component }}-svc
  labels:
    service: {{ .Values.environment }}-{{ .Values.component }}
spec:
  selector:
    component: {{ .Values.environment }}-{{ .Values.component }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http