apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-resource-https
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
      - web.example.com
      - api.example.com
    secretName: example-com-tls
  rules:
    - host: web.example.com
      http:
        paths:
         - backend:
            serviceName: example-web-svc
            servicePort: 80
    - host: api.example.com
      http:
        paths:
         - backend:
             serviceName: example-api-svc
             servicePort: 81