# {{ .Values. }}
environment: example
component: mysql

replicaCount: 3

service:
  type: ClusterIP
  port: 3306
  targetPort: 3306

registry: eu.gcr.io/example-project

image:
  tag: latest
  pullPolicy: IfNotPresent